### ISSUE TITLE
Comentarios sobre el esquema de la base de datos.

### ISSUE THREAD

**Issue by sectario** [sectario/ERPparaPeque-osMercados#1]
1. Las tabla de cliente y proveedor se pueden unificar en una llamada terceros y simplemente que tengan una marcación en la que se les asigna 1 para cliente y 0 si es proveedor.
2. A qué hace referencia la tabla tipo de dirección?
3. En la tabla de contacto se pueden agregar los campos de teléfono e email. El capo de email puede ser null porque las personas pueden tener varios teléfonos, pero un solo correo y viceversa.
4. Crear una tabla adicional que se llame Kardex. que tenga los siguientes campos id registro, prymary_key_factura, id_factura, id_producto, unidades, valor_unitario. En esta tabla se lleva el histórico de la compra y venta del producto.
5. Crear una tabla que se llame documentos. Y addicionar Tipo como llave primaria, naturaleza (Tipo byte) (Campos D, C y N) y grupo. En esa tabla vamos a almacenar los siguientes campos (FV, D, 1) y (FC,C,1)
6. Crear una tabla factura_venta y factura_compra y adicionar los siguientes campos: prymary_key_factura (FV ó FC), id_factura, id_tercero, subtotal, impo_consumo, iva y total.
7. Adicionar una tabla de usuarios son los siguientes campos id_tercero, username, password, grupo y subgrupo.

**Comment by sectario** [comment]
> 1. Las tabla de cliente y proveedor se pueden unificar en una llamada terceros y simplemente que tengan una marcación en la que se les asigna 1 para cliente y 0 si es proveedor.
> 2. A qué hace referencia la tabla tipo de dirección?
> 3. En la tabla de contacto se pueden agregar los campos de teléfono e email. El capo de email puede ser null porque las personas pueden tener varios teléfonos, pero un solo correo y viceversa.
> 4. Crear una tabla adicional que se llame Kardex. que tenga los siguientes campos id registro, prymary_key_factura, id_factura, id_producto, unidades, valor_unitario. En esta tabla se lleva el histórico de la compra y venta del producto.
> 5. Crear una tabla que se llame documentos. Y addicionar Tipo como llave primaria, naturaleza (Tipo byte) (Campos D, C y N) y grupo. En esa tabla vamos a almacenar los siguientes campos (FV, D, 1) y (FC,C,1)
> 6. Crear una tabla factura_venta y factura_compra y adicionar los siguientes campos: prymary_key_factura (FV ó FC), id_factura, id_tercero, subtotal, impo_consumo, iva y total.
> 7. Adicionar una tabla de usuarios son los siguientes campos id_tercero, username, password, grupo y subgrupo.

**Comment by desinnio** [comment]
Las tabla de cliente y proveedor se pueden unificar en una llamada terceros y simplemente que tengan una marcación en la que se les asigna 1 para cliente y 0 si es proveedor.
	Ok_hecho
A qué hace referencia la tabla tipo de dirección?
	Se elimino
En la tabla de contacto se pueden agregar los campos de teléfono e email. El capo de email puede ser null porque las personas pueden tener varios teléfonos, pero un solo correo y viceversa.
	Ok_hecho
Crear una tabla adicional que se llame Kardex. que tenga los siguientes campos id registro, prymary_key_factura, id_factura, id_producto, unidades, valor_unitario. En esta tabla se lleva el histórico de la compra y venta del producto.
	Ok_hecho
Crear una tabla que se llame documentos. Y addicionar Tipo como llave primaria, naturaleza (Tipo byte) (Campos D, C y N) y grupo. En esa tabla vamos a almacenar los siguientes campos (FV, D, 1) y (FC,C,1)
	Se creo la tabla pero NO los campos
Crear una tabla factura_venta y factura_compra y adicionar los siguientes campos: prymary_key_factura (FV ó FC), id_factura, id_tercero, subtotal, impo_consumo, iva y total.
	Se crearon dos tablas de fac_venta y otra factura_compra
Adicionar una tabla de usuarios son los siguientes campos id_tercero, username, password, grupo y subgrupo.
	ok_hecho

Nota: se actualizaron los archivos en GitHub

**Comment by sectario** [comment]
### **Todos los cambios los realice creando una nueva rama para que tengas oportunidad de visualizar.**

Hola. @desinnio y @DayisDev , le hice un par de modificaciones al modelo de la base de datos uniendo las facturas en una tabla llamada documentos_facturacion donde se van a diferenciar en el tipo siendo FV factura de venta y FC factura de compra. Adicioné tipo de tercero, modifique la tabla usuarios, se elimina la tabla tipo contacto rediseñé la tabla detalle_factura dejándola como items_factura. Finalmente ajuste algunas relaciones y llaves primarias.


Algunos aspectos a tener en cuenta.

- Usuarios => estado valor 0 inactivo /  1 activo
- Usuarios pasa a ser una relación de 1:1 porque no es lógico que un tercero tenga varios usuarios. Es mejor manejar un único usuario y tener un sistema de permisos.
- En varios casos no se requieren llaves primarias como los es en items_factura que se toma una llave foránea.
- Los demás ajustes los puedes comparar con la rama principal.

Cualquier cosa me comentan.
